// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFileTree(arg1:string,arg2:boolean):Promise<main.FileNode>;

export function CreateFileTreeWithDetails(arg1:string):Promise<main.FileNodeWithDetails>;

export function Greet(arg1:string):Promise<string>;
