// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFileTree(arg1, arg2) {
  return window['go']['main']['App']['CreateFileTree'](arg1, arg2);
}

export function CreateFileTreeWithDetails(arg1) {
  return window['go']['main']['App']['CreateFileTreeWithDetails'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
